### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by Lrr57** [mczhuge/ICON#8]
Traceback (most recent call last):
  File "main/train.py", line 226, in <module>
    train(dataset, parser)
  File "main/train.py", line 132, in train
    out2, out3, out4, out5, pose = net(image)            
  File "/usr/local/anaconda3/envs/u2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/senlinren/LR/ICON-main/main/model/icon/icon.py", line 221, in forward
    x1 = self.dfa1(x1) 
  File "/usr/local/anaconda3/envs/u2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/senlinren/LR/ICON-main/main/model/icon/modules.py", line 134, in forward
    p3 = self.atrConv(f)
  File "/usr/local/anaconda3/envs/u2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/envs/u2/lib/python3.7/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/usr/local/anaconda3/envs/u2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/anaconda3/envs/u2/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 1240, in forward
    return F.prelu(input, self.weight)
RuntimeError: expected scalar type Half but found Float

**Comment by mczhuge** [comment]
Check your apex version and https://github.com/mczhuge/ICON/blob/main/main/train.py#121.

But please notice, it may influence the performance.

**Comment by mczhuge** [comment]
Hi, @Lrr57 . Have you solved this issue?

**Comment by Ayews** [comment]
I met the same problem.
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    train(dataset, parser)
  File "train.py", line 132, in train
    out2, out3, out4, out5, pose = net(image)            
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/Models/icon/icon.py", line 216, in forward
    x1 = self.dfa1(x2)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/Models/icon/modules.py", line 131, in forward
    p3 = self.atrConv(f)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1226, in forward
    return F.prelu(input, self.weight)
RuntimeError: expected scalar type Half but found Float

Although I can run code without apex(change data type in dataset.py), it will lead to terrible performance.
I will try re-install apex and pytorch.

**Comment by mczhuge** [comment]
@Ayews Actually, I often met this problem in "Pytorch+Apex" based project. Yes, you can double check the environment:

```
[Python 3.5](https://www.python.org/)
[Pytorch 1.3](http://pytorch.org/)
[OpenCV 4.0](https://opencv.org/)
[Numpy 1.15](https://numpy.org/)
[TensorboardX](https://github.com/lanpa/tensorboardX)
[Apex](https://github.com/NVIDIA/apex)
```

**Comment by Ayews** [comment]
@mczhuge Oops... I can't find pytorch1.3 on its website, and deploying a related CUDA environment is also a problem, I guess pytorch1.3 cant support CUDA 11.3? I also wonder if you install the apex with cuda/cpp extensions or not? Thanks for your help in providing this information. 
I think it is normal for pytorch+apex to have problems because apex installation does not depend on a strict environment, any python version, pytorch vision, CUDA vision can install it, so whether it works or not is unknown to some extent.
but I succeeded in running ICON with several changes:
1. The error above seemed to be caused by the incompatibility between the current apex and prelu, I replaced prelu with relu;
2. When I fixed pre error, I met this new error:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
    fit([60],model,lr,train_dl,method)
  File "/root/workspace/train.py", line 142, in fit
    loss = train_one_epoch(epoch,epochs[st],model,train_dl)
  File "/root/workspace/train.py", line 96, in train_one_epoch
    out2, out3, out4, out5, pose = model(images)            
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/icon.py", line 215, in forward
    x2  = self.ice1(in1=x2, in2=x1, in3=x3)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/workspace/Models/icon/modules.py", line 173, in forward
    x = F.relu(self.bn_cross(self.conv_cross(x))) #[B, C, H, W]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/root/miniconda3/lib/python3.8/site-packages/apex-0.1-py3.8-linux-x86_64.egg/apex/amp/wrap.py", line 21, in wrapper
    args[i] = utils.cached_cast(cast_fn, args[i], handle.cache)
  File "/root/miniconda3/lib/python3.8/site-packages/apex-0.1-py3.8-linux-x86_64.egg/apex/amp/utils.py", line 97, in cached_cast
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range

 I read this source code from utils and found this is an inspection measure, I just remark it with '''.

def cached_cast(cast_fn, x, cache):
    if is_nested(x):
        return type(x)([cached_cast(y) for y in x])
    if x in cache:
        cached_x = cache[x]
        '''
        _if x.requires_grad and cached_x.requires_grad:
            # Make sure x is actually cached_x's autograd parent.
            if cached_x.grad_fn.next_functions[1][0].variable is not x:
                raise RuntimeError("x and cache[x] both require grad, but x is not "
                                   "cache[x]'s parent.  This is likely an error.")_
        '''
        # During eval, it's possible to end up caching casted weights with
        # requires_grad=False.  On the next training iter, if cached_x is found
        # and reused from the cache, it will not actually have x as its parent.
        # Therefore, we choose to invalidate the cache (and force refreshing the cast)
        # if x.requires_grad and cached_x.requires_grad do not match.
        #
        # During eval (i.e. running under with torch.no_grad()) the invalidation
        # check would cause the cached value to be dropped every time, because
        # cached_x would always be created with requires_grad=False, while x would
        # still have requires_grad=True.  This would render the cache effectively
        # useless during eval.  Therefore, if we are running under the no_grad()
        # context manager (torch.is_grad_enabled=False) we elide the invalidation
        # check, and use the cached value even though its requires_grad flag doesn't
        # match.  During eval, we don't care that there's no autograd-graph
        # connection between x and cached_x.
        if torch.is_grad_enabled() and x.requires_grad != cached_x.requires_grad:
            del cache[x]
        else:
            return cached_x
    casted_x = cast_fn(x)
    cache[x] = casted_x
    return casted_x
****
Anyway, the training code started running. I'm looking forward to its results

**Comment by mczhuge** [comment]
@Ayews I think the most important thing is to check your CUDA, CUDNN, torch, Apex version. If they match, I think there is no problem. You could try SWIN/PVT encoder first.

**Comment by mczhuge** [comment]
> ched_cast(cast_fn, x, cache):
> if is_nested(x):
> return type(x)([cached_cast(y) for y in x])
> if x in cache:
> cached_x = cache[x]
> '''
> _if x.requires_grad and cached_x.requires_grad: # Make sure x is actually cached_x's autograd parent. if cached_x.grad_fn.next_functions[1][0].variable is not x: raise RuntimeError("x and cache[x] both require grad, but x is not " "cache[x]'s parent. This is likely an error.")_
> '''
> # During eval, it's possible to end up caching casted weights with
> # requires_grad=False. On the next training iter, if cached_x is found
> # and reused from the cache, it will not actually have x as its parent.
> # Therefore, we choose to invalidate the cache (and force refreshing the cast)
> # if x.requires_grad and cached_x.requires_grad do not match.
> #
> # During eval (i.e. running under with torch.no_grad()) the invalidation
> # check would cause the cached value to be dropped every time, because
> # cached_x would always be created with requires_grad=False, while x would
> # still have requires_grad=True. This would render the cache effectively
> # useless during eval. Therefore, if we are running under the no_grad()
> # context manager (torch.is_grad_enabled=False) we elide the invalidation
> # check, and use the cached value even though its requires_grad flag doesn't
> # match. During eval, we don't care that there's no autograd-graph
> # connection between x and cached_x.
> if torch.is_grad_enabled() and x.requires_grad != cached_x.requires_grad:
> del cache[x]
> else:
> return cached_x
> casted_x = cast_fn(x)
> cache[x] = casted_x

There is a quick method to solve the first problem, that change the 'O1' to 'O2' in https://github.com/mczhuge/ICON/blob/main/main/train.py#121.

But as I mentioned, it would inflect the performance. So I am now trying to solve this issue.

**Comment by mczhuge** [comment]
@Ayews  There is a quick method to solve the first problem, that change the 'O1' to 'O2' in https://github.com/mczhuge/ICON/blob/main/main/train.py#121.

But as I mentioned, it would inflect the performance. So I am now trying to solve this issue.

**Comment by zqy1** [comment]
@mczhuge I also met this problem.Is it repaired now? Thanks.

**Comment by mczhuge** [comment]
@zqy1 
Hi, could you re-build your environment following:   https://github.com/mczhuge/ICON/tree/main/util
And if there is still a problem, please let me know.
My wechat: tjpxiaoming if you need more help

**Comment by mczhuge** [comment]
As suggested by [yuqiuyuqiu](https://github.com/yuqiuyuqiu).
Use the PyTorch version <= 1.10.1
